engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,dist"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: true
        exceptions: "$id,$sm,$em,$qb,$e"
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- config/**/*
