language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - composer install --prefer-source

script:
  - phpunit --configuration module/User/test/phpunit.xml
  - phpunit --configuration module/Decision/test/phpunit.xml
  - ./web orm:validate-schema
