version: '3.5'

services:
    mysql:
        image: mysql:5.5
        env_file:
            - .env
        volumes:
            - gewisweb_mysql:/var/lib/mysql:rw
        networks:
            - gewisweb_network
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - gewisweb_network
        ports:
            - "8080:80"
    nginx:
        build: docker/nginx
        ports:
            - "80:9200"
    web:
        build: .
        depends_on:
            - mysql
        entrypoint: ["/bin/sh", "/code/docker-entrypoint.override.sh"]

volumes:
    gewisweb_mysql:
