version: '3.5'

services:
    nginx:
        image: web.docker-registry.gewis.nl/gewisweb_nginx:latest
        env_file:
            - .env
        #        environment:
        #            - NGINX_REQUIRE_AUTH=
        depends_on:
            - web
            - glide
            - matomo
        volumes:
            - gewisweb_public:/code/public:ro
            - gewisweb_glide_public:/glide/public:ro
            - gewisweb_logs:/etc/nginx/logs:rw
        networks:
            - gewisweb_network
        ports:
            - "9200:9200"
            - "9201:9201"
            - "9202:9202"
        restart: unless-stopped
    web:
        image: web.docker-registry.gewis.nl/gewisweb_web:production
        env_file:
            - .env
#        environment:
#            - APP_ENV=
#            - COOKIE_DOMAIN=
#            - GLIDE_HOST=
#            - GLIDE_KEY=
#            - DOCKER_GOOGLE_API_KEY=
#            - DOCKER_GOOGLE_CALENDAR_KEY=
#            - DOCKER_SUPREMUM_API_KEY=
#            - DOCKER_DB_HOST=
#            - DOCKER_DB_PORT=
#            - DOCKER_DB_USERNAME=
#            - DOCKER_DB_PASSWORD=
#            - DOCKER_DB_DATABASE=
#            - DOCKER_DB2_HOST=
#            - DOCKER_DB2_PORT=
#            - DOCKER_DB2_USERNAME=
#            - DOCKER_DB2_PASSWORD=
#            - DOCKER_DB2_DATABASE=
#            - SSH_USERNAME=
#            - SSH_PASSWORD=
        depends_on:
            - memcached
            - postfix
        volumes:
            - gewisweb_data:/code/data:rw
            - gewisweb_public:/code/public:rw
        networks:
            - gewisweb_network
        restart: unless-stopped
    glide:
        image: web.docker-registry.gewis.nl/gewisweb_glide:latest
        env_file:
            - .env
#        environment:
#            - GLIDE_HOST=
#            - GLIDE_KEY=
        volumes:
            - gewisweb_glide_public:/glide/public:rw
            - gewisweb_public:/code/public:rw
        networks:
            - gewisweb_network
        restart: unless-stopped
    postfix:
        image: juanluisbaptiste/postfix
        env_file:
            - .env
#        environment:
#            - SMTP_SERVER=
#            - SMTP_PORT=
#            - SMTP_USERNAME=
#            - SMTP_PASSWORD=
#            - SERVER_HOSTNAME=
        networks:
            - gewisweb_network
        restart: unless-stopped
    memcached:
        image: memcached
        entrypoint: ['memcached', '-m 256']
        networks:
            - gewisweb_network
        restart: unless-stopped
    matomo:
        image: web.docker-registry.gewis.nl/gewisweb_matomo:latest
        env_file:
            - .env
#        environment:
#            - MATOMO_DATABASE_HOST=
#            - MATOMO_DATABASE_PORT=
#            - MATOMO_DATABASE_USERNAME=
#            - MATOMO_DATABASE_PASSWORD=
#            - MATOMO_DATABASE_DBNAME=
        networks:
            - gewisweb_network
        restart: unless-stopped

volumes:
    gewisweb_data:
    gewisweb_public:
    gewisweb_glide_public:
    gewisweb_logs:

networks:
    gewisweb_network:
