version: '3.5'

services:
    mysql:
        image: mariadb:10
        env_file:
            - .env
        volumes:
            - gewisweb_mysql:/var/lib/mysql:rw
        networks:
            - gewisweb_network
        ports:
            - "3306:3306"
        restart: unless-stopped
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - gewisweb_network
        ports:
            - "8080:80"
        restart: unless-stopped
    nginx:
        build: docker/nginx
        ports:
            - "80:9200"
            - "81:9201"
            - "82:9202"
    web:
        image: web.docker-registry.gewis.nl/gewisweb_web:development
        build:
            dockerfile: docker/web/development/Dockerfile
            context: .
        depends_on:
            - mysql
    glide:
        build: docker/glide
    matomo:
        build: docker/matomo
        depends_on:
            - mysql

volumes:
    gewisweb_mysql:
