version: '3.5'

services:
    mysql:
        image: mysql:5.5
        env_file:
            - .env
        volumes:
            - gewisweb_mysql:/var/lib/mysql:rw
        networks:
            - gewisweb_network
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - gewisweb_network
        ports:
            - "8080:80"
    nginx:
        build: docker/nginx
        ports:
            - "80:9200"
    web:
        image: web.docker-registry.gewis.nl/gewisweb_web:development
        build:
            dockerfile: docker/web/development/Dockerfile
            context: .
        depends_on:
            - mysql

volumes:
    gewisweb_mysql:
