version: '3.5'

services:
    nginx:
        image: web.docker-registry.gewis.nl/gewisweb_nginx:latest
        env_file:
            - .env
#        environment:
#            - NGINX_REQUIRE_AUTH=
        depends_on:
            - web
        volumes:
            - gewisweb_public:/code/public:ro
            - gewisweb_logs:/etc/nginx/logs:rw
        networks:
            - gewisweb_network
        ports:
            - "9200:9200"
        restart: unless-stopped
    web:
        image: web.docker-registry.gewis.nl/gewisweb_web:production
        env_file:
            - .env
#        environment:
#            - APP_ENV=
#            - DOCKER_MAIL_HOST=
#            - DOCKER_MAIL_PORT=
#            - DOCKER_MAIL_USERNAME=
#            - DOCKER_MAIL_PASSWORD=
#            - DOCKER_GOOGLE_API_KEY=
#            - DOCKER_GOOGLE_CALENDAR_KEY=
#            - DOCKER_DB_HOST=
#            - DOCKER_DB_PORT=
#            - DOCKER_DB_USERNAME=
#            - DOCKER_DB_PASSWORD=
#            - DOCKER_DB_DATABASE=
#            - DOCKER_DB2_HOST=
#            - DOCKER_DB2_PORT=
#            - DOCKER_DB2_USERNAME=
#            - DOCKER_DB2_PASSWORD=
#            - DOCKER_DB2_DATABASE=
        volumes:
            - gewisweb_data:/code/data:rw
            - gewisweb_public:/code/public:rw
        networks:
            - gewisweb_network
        restart: unless-stopped

volumes:
    gewisweb_data:
    gewisweb_public:
    gewisweb_logs:

networks:
    gewisweb_network:
