version: '3.5'

services:
    nginx:
        image: web.docker-registry.gewis.nl/gewisweb_nginx:latest
        env_file:
            - .env
        depends_on:
            - web
        volumes:
            - gewisweb_public:/public:ro
            - gewisweb_logs:/etc/nginx/logs:rw
        networks:
            - gewisweb_network
        ports:
            - "9200:9200"
        restart: unless-stopped
    web:
        image: web.docker-registry.gewis.nl/gewisweb_web:latest
        env_file:
            - .env
        volumes:
            - gewisweb_data:/data:rw
            - gewisweb_public:/public:rw
        networks:
            - gewisweb_network
        restart: unless-stopped

volumes:
    gewisweb_data:
    gewisweb_public:
    gewisweb_logs:

networks:
    gewisweb_network:
