name: PHP Coding Standards

# Only run this action when pushing to master or on pull requests (creation, synchronisation, and reopening).
on:
    push:
        branches:
            - master
    pull_request:

# Cancel running jobs that have become stale through updates to the ref (e.g., pushes to a pull request).
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    php-codesniffer:
        uses: 'GEWIS/gewisphp-coding-standards/.github/workflows/coding-standards.yml@1.0.0'

