name: Docker Image CI

# Only run this action when pushing to main (development release) or on tagged versions (latest release).
on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'

# Cancel running jobs that have become stale through updates to the ref (e.g., pushes to a pull request).
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    IMAGE_NAME_GLIDE: ${{ vars.ABC_DOCKER_REGISTRY }}/web/gewisweb/glide
    IMAGE_NAME_MATOMO: ${{ vars.ABC_DOCKER_REGISTRY }}/web/gewisweb/matomo
    IMAGE_NAME_NGINX: ${{ vars.ABC_DOCKER_REGISTRY }}/web/gewisweb/nginx
    IMAGE_NAME_WEB: ${{ vars.ABC_DOCKER_REGISTRY }}/web/gewisweb/web
    IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to Docker Registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ vars.ABC_DOCKER_REGISTRY }}
                    username: ${{ secrets.SVC_GH_ABCWEB_USERNAME }}
                    password: ${{ secrets.SVC_GH_ABCWEB_PWD }}

            -   name: Build and push web image
                uses: docker/build-push-action@v6
                with:
                    build-args: GIT_COMMIT=${{ github.sha }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    context: .
                    file: ${{ env.IS_RELEASE && './docker/web/production/Dockerfile' || './docker/web/development/Dockerfile' }}
                    platforms: linux/amd64
                    push: true
                    tags: ${{ format('{0}:{1}', env.IMAGE_NAME_WEB, env.IS_RELEASE && format('{0},{1}:latest', github.ref_name, env.IMAGE_NAME_WEB) || 'development') }}

            -   name: Build and push glide image
                uses: docker/build-push-action@v6
                with:
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    context: ./docker/glide
                    file: ./docker/glide/Dockerfile
                    platforms: linux/amd64
                    push: true
                    tags: ${{ format('{0}:{1}', env.IMAGE_NAME_GLIDE, env.IS_RELEASE && format('{0},{1}:latest', github.ref_name, env.IMAGE_NAME_GLIDE) || 'development') }}

            -   name: Build and push matomo image
                uses: docker/build-push-action@v6
                with:
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    context: ./docker/matomo
                    file: ./docker/matomo/Dockerfile
                    platforms: linux/amd64
                    push: true
                    tags: ${{ format('{0}:{1}', env.IMAGE_NAME_MATOMO, env.IS_RELEASE && format('{0},{1}:latest', github.ref_name, env.IMAGE_NAME_MATOMO) || 'development') }}

            -   name: Build and push nginx image
                uses: docker/build-push-action@v6
                with:
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    context: ./docker/nginx
                    file: ./docker/nginx/Dockerfile
                    platforms: linux/amd64
                    push: true
                    tags: ${{ format('{0}:{1}', env.IMAGE_NAME_NGINX, env.IS_RELEASE && format('{0},{1}:latest', github.ref_name, env.IMAGE_NAME_NGINX) || 'development') }}
