name: PHP Static Analysis with Psalm

# Only run this action on pull requests (creation, synchronisation, and reopening).
on: [pull_request]

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout head branch
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: calendar, curl, exif, gd, intl, opcache, pgsql, pdo_mysql, pdo_pgsql, zip, imagick, memcached, xdebug

            -   name: Get Composer cache directory
                id: composer-cache-head
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache-head.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Extract configuration files
                run: |
                    cp config/autoload/doctrine.local.development.php.dist config/autoload/doctrine.local.php
                    cp config/autoload/laminas-developer-tools.local.php.dist config/autoload/laminas-developer-tools.local.php
                    cp config/autoload/local.development.php.dist config/autoload/local.php

            -   name: Check out master
                run: |
                    git fetch --all
                    git update-ref refs/heads/temp-psalmpr refs/remotes/origin/master
                    git checkout --detach temp-psalmpr

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Load environment variables
                uses: c-py/action-dotenv-to-setenv@v3
                with:
                    env-file: .env.dist

            -   name: Generate Psalm Baseline
                run: |
                    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><files/>" > psalm/psalm-baseline.xml
                    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><files/>" > psalm/psalm-baseline-pr.xml
                    vendor/bin/psalm --set-baseline=psalm/psalm-baseline-pr.xml --no-diff --no-cache --no-progress || true

            -   name: Check out new branch
                run: |
                    git checkout -- psalm/psalm-baseline.xml
                    git checkout --theirs -- config/modules.config.php
                    git checkout -

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Load environment variables
                uses: c-py/action-dotenv-to-setenv@v3
                with:
                    env-file: .env.dist

            -   name: Run Psalm
                run: |
                    vendor/bin/psalm  --no-diff --no-cache --no-progress --output-format=github
